/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsApiRouteImport } from './routes/docs/api'
import { Route as ApiIngestRouteImport } from './routes/api/ingest'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthedAppIndexRouteImport } from './routes/_authed/app/index'
import { Route as ApiInternalRetentionRouteImport } from './routes/api/internal/retention'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthedAppSettingsRouteImport } from './routes/_authed/app/settings'
import { Route as AuthedAppKeysRouteImport } from './routes/_authed/app/keys'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DocsRoute,
} as any)
const ApiIngestRoute = ApiIngestRouteImport.update({
  id: '/api/ingest',
  path: '/api/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppIndexRoute = AuthedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiInternalRetentionRoute = ApiInternalRetentionRouteImport.update({
  id: '/api/internal/retention',
  path: '/api/internal/retention',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppSettingsRoute = AuthedAppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppKeysRoute = AuthedAppKeysRouteImport.update({
  id: '/app/keys',
  path: '/app/keys',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ingest': typeof ApiIngestRoute
  '/docs/api': typeof DocsApiRoute
  '/app/keys': typeof AuthedAppKeysRoute
  '/app/settings': typeof AuthedAppSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/retention': typeof ApiInternalRetentionRoute
  '/app/': typeof AuthedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ingest': typeof ApiIngestRoute
  '/docs/api': typeof DocsApiRoute
  '/app/keys': typeof AuthedAppKeysRoute
  '/app/settings': typeof AuthedAppSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/retention': typeof ApiInternalRetentionRoute
  '/app': typeof AuthedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ingest': typeof ApiIngestRoute
  '/docs/api': typeof DocsApiRoute
  '/_authed/app/keys': typeof AuthedAppKeysRoute
  '/_authed/app/settings': typeof AuthedAppSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/retention': typeof ApiInternalRetentionRoute
  '/_authed/app/': typeof AuthedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/docs'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/api/health'
    | '/api/ingest'
    | '/docs/api'
    | '/app/keys'
    | '/app/settings'
    | '/api/auth/$'
    | '/api/internal/retention'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/docs'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/api/health'
    | '/api/ingest'
    | '/docs/api'
    | '/app/keys'
    | '/app/settings'
    | '/api/auth/$'
    | '/api/internal/retention'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/demo'
    | '/docs'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/api/health'
    | '/api/ingest'
    | '/docs/api'
    | '/_authed/app/keys'
    | '/_authed/app/settings'
    | '/api/auth/$'
    | '/api/internal/retention'
    | '/_authed/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  DemoRoute: typeof DemoRoute
  DocsRoute: typeof DocsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiIngestRoute: typeof ApiIngestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiInternalRetentionRoute: typeof ApiInternalRetentionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/api/ingest': {
      id: '/api/ingest'
      path: '/api/ingest'
      fullPath: '/api/ingest'
      preLoaderRoute: typeof ApiIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/app/': {
      id: '/_authed/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthedAppIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/internal/retention': {
      id: '/api/internal/retention'
      path: '/api/internal/retention'
      fullPath: '/api/internal/retention'
      preLoaderRoute: typeof ApiInternalRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/app/settings': {
      id: '/_authed/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthedAppSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/app/keys': {
      id: '/_authed/app/keys'
      path: '/app/keys'
      fullPath: '/app/keys'
      preLoaderRoute: typeof AuthedAppKeysRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAppKeysRoute: typeof AuthedAppKeysRoute
  AuthedAppSettingsRoute: typeof AuthedAppSettingsRoute
  AuthedAppIndexRoute: typeof AuthedAppIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAppKeysRoute: AuthedAppKeysRoute,
  AuthedAppSettingsRoute: AuthedAppSettingsRoute,
  AuthedAppIndexRoute: AuthedAppIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface DocsRouteChildren {
  DocsApiRoute: typeof DocsApiRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsApiRoute: DocsApiRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  DemoRoute: DemoRoute,
  DocsRoute: DocsRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiIngestRoute: ApiIngestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiInternalRetentionRoute: ApiInternalRetentionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
