/**
 * Hosted blockrate.app Postgres schema — single source of truth for the
 * web app's database. apps/web OWNS all hosted-deployment tables (revision 2
 * decision: no schema split with packages/server). The events/tenants
 * definitions are duplicated from packages/server/src/schema.postgres.ts
 * (~30 lines, by explicit decision) so each deployment has unambiguous
 * ownership of its own migration history.
 *
 * Better Auth's tables (users, sessions, accounts, verification) are
 * generated by `bunx @better-auth/cli generate` into ./auth-schema.ts and
 * re-exported below.
 */

import { sql } from "drizzle-orm";
import {
  integer,
  pgEnum,
  pgTable,
  serial,
  text,
  timestamp,
  index,
} from "drizzle-orm/pg-core";

// ─── Re-export Better Auth tables ───────────────────────────────────────
// auth-schema.ts is generated by `bun run auth:generate`. It will be created
// during Phase 1.4 step 3. Until then, this re-export is a no-op.
export * from "./auth-schema";

// ─── Block-rate event storage ───────────────────────────────────────────

export const statusEnum = pgEnum("block_rate_status", ["loaded", "blocked"]);

/**
 * One row per service that reports block-rate data. In Phase 2 this will be
 * keyed off api_keys instead of being a flat tenants table — for now,
 * matches the packages/server shape so existing PostgresStore queries work.
 */
export const tenants = pgTable("tenants", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  apiKey: text("api_key").notNull().unique(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .default(sql`now()`),
});

/**
 * Per-provider check events. user_agent is stored TRUNCATED to browser
 * family + major version (via packages/server's truncateUserAgent helper).
 * Never raw UA — see docs/design.md and the parent plan's privacy posture.
 */
export const events = pgTable(
  "events",
  {
    id: serial("id").primaryKey(),
    tenantId: integer("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    service: text("service").notNull().default("default"),
    timestamp: timestamp("timestamp", { withTimezone: true }).notNull(),
    url: text("url").notNull(),
    userAgent: text("user_agent").notNull(),
    provider: text("provider").notNull(),
    status: statusEnum("status").notNull(),
    latency: integer("latency").notNull(),
  },
  (t) => ({
    byTenantService: index("idx_events_tenant_service").on(
      t.tenantId,
      t.service,
      t.timestamp
    ),
    byProvider: index("idx_events_provider").on(t.provider),
  })
);

export type Tenant = typeof tenants.$inferSelect;
export type Event = typeof events.$inferSelect;
export type NewEvent = typeof events.$inferInsert;
